[package]
name = "rust-rewrite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ascii_converter = "0.3.0"
clap = "4.4.8"
